# netlify.toml
# Netlify configuration file

[build]
  # Build command (if you have a build process, otherwise leave empty)
  command = ""
  
  # Directory to publish (your website files)
  publish = "."
  
  # Directory where Netlify Functions are located
  functions = "netlify/functions"

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set these in Netlify dashboard)
# OPENAI_API_KEY = "your-key-here"